services:
  postgres:
    image: postgres:16-alpine
    container_name: hdps_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hoja_de_parra_spitz
    ports:
      - '5432:5432'
    volumes:
      - hdps_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  hdps_postgres_data:
